apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: gg7inf40r-nodejs 
  janus-idp.io/tekton: gg7inf40r-nodejs
  backstage.io/kubernetes-id: gg7inf40r-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: gg7inf40r-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml