apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: gg7inf40r-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: gg7inf40r-nodejs 
  name: gg7inf40r-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: gg7inf40r-nodejs 
